name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk wget
        sudo apt-get install -y autoconf libtool pkg-config zlib1g-dev
        sudo apt-get install -y libncurses5-dev libncursesw5-dev libtinfo5
        sudo apt-get install -y libffi-dev libssl-dev
    
    - name: Install Python dependencies
      run: |
        pip install buildozer cython==0.29.33
    
    - name: Build APK with Buildozer
      run: |
        buildozer android debug
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: ytaudiodownloader-apk
        path: bin/*.apk
        if-no-files-found: error
    
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
